
## Marketing Problem

In [1]:
import mysql.connector
import pandas as pd

In [2]:
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="your_password"
)
print(mydb)

<mysql.connector.connection_cext.CMySQLConnection object at 0x0000023524D33E20>

In [3]:
mycursor = mydb.cursor()
mycursor.execute("CREATE DATABASE IF NOT EXISTS mcdonalds_reviews")

In [4]:
mycursor = mydb.cursor()
mycursor.execute("SHOW DATABASES")
for x in mycursor:
    print(x)

('ap',)
('ap2',)
('bluewave',)
('coffee_shop_project',)
('ex',)
('information_schema',)
('mcdonalds_reviews',)
('my_guitar_shop',)
('mysql',)
('olist',)
('om',)
('performance_schema',)
('pokemon',)
('slcwinter2023',)
('sys',)
('test123',)

In [5]:
import re

In [6]:
data = pd.read_csv("https://raw.githubusercontent.com/Amaljozef7/Datafile/main/McDonald_s_Reviews.csv",encoding='ISO-8859-1')

In [7]:
data.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating
0,1,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",3 months ago,Why does it look like someone spit on my food?...,1 star
1,2,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,It'd McDonalds. It is what it is as far as the...,4 stars
2,3,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Made a mobile order got to the speaker and che...,1 star
3,4,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",a month ago,My mc. Crispy chicken sandwich was ï¿½ï¿½ï¿½ï¿...,5 stars
4,5,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",2 months ago,"I repeat my order 3 times in the drive thru, a...",1 star

In [8]:
# Handle special characters in reviews
data['review'] = data['review'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', '', x))

In [9]:
# Convert ratings to numerical values
data['rating'] = data['rating'].apply(lambda x: int(x.split()[0]))

In [10]:
print(data.columns)

Index(['reviewer_id', 'store_name', 'category', 'store_address', 'latitude ',
       'longitude', 'rating_count', 'review_time', 'review', 'rating'],
      dtype='object')

In [11]:
data = data.rename(columns={'latitude ': 'latitude'})

In [12]:
data.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating
0,1,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",3 months ago,Why does it look like someone spit on my food\...,1
1,2,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Itd McDonalds It is what it is as far as the f...,4
2,3,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Made a mobile order got to the speaker and che...,1
3,4,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",a month ago,My mc Crispy chicken sandwich was customer se...,5
4,5,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",2 months ago,I repeat my order 3 times in the drive thru an...,1

In [13]:
address_components = data['store_address'].str.split(', ', expand=True)

In [14]:
address_components.head()

                  0       1         2              3     4
0  13749 US-183 Hwy  Austin  TX 78750  United States  None
1  13749 US-183 Hwy  Austin  TX 78750  United States  None
2  13749 US-183 Hwy  Austin  TX 78750  United States  None
3  13749 US-183 Hwy  Austin  TX 78750  United States  None
4  13749 US-183 Hwy  Austin  TX 78750  United States  None

In [19]:
city = address_components[1]

In [20]:
city.head()

0    Austin
1    Austin
2    Austin
3    Austin
4    Austin
Name: 1, dtype: object

In [21]:
data["city"]=city

In [22]:
state = address_components[2].str.split(' ', expand=True)[0]

In [23]:
state.head()

0    TX
1    TX
2    TX
3    TX
4    TX
Name: 0, dtype: object

In [24]:
data["state"]=state

In [25]:
data['country'] = address_components[3]

In [26]:
data.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating,city,state,country
0,1,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",3 months ago,Why does it look like someone spit on my food\...,1,Austin,TX,United States
1,2,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Itd McDonalds It is what it is as far as the f...,4,Austin,TX,United States
2,3,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Made a mobile order got to the speaker and che...,1,Austin,TX,United States
3,4,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",a month ago,My mc Crispy chicken sandwich was customer se...,5,Austin,TX,United States
4,5,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",2 months ago,I repeat my order 3 times in the drive thru an...,1,Austin,TX,United States

In [30]:
def time_to_days(time_str):
    parts = time_str.split()
    # Replace 'a' or 'an' with '1' if it's the first part of the string
    if parts[0] in ('a', 'an'):
        parts[0] = '1'
    try:
        num = int(parts[0])
    except ValueError:
        return 0
    unit = parts[1].lower()
    # Convert the time unit to days
    if 'day' in unit:
        return num
    elif 'week' in unit:
        return num * 7
    elif 'month' in unit:
        return num * 30  # Approximation, as months have varying number of days
    elif 'year' in unit:
        return num * 365  # Approximation, ignoring leap years
    else:
        return 0

In [31]:
review_time_in_days = data['review_time'].apply(time_to_days)

In [32]:
review_time_in_days.head()

0    90
1     5
2     5
3    30
4    60
Name: review_time, dtype: int64

In [33]:
data['review_time_in_days']=review_time_in_days

In [34]:
data.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating,city,state,country,review_time_in_days
0,1,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",3 months ago,Why does it look like someone spit on my food\...,1,Austin,TX,United States,90
1,2,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Itd McDonalds It is what it is as far as the f...,4,Austin,TX,United States,5
2,3,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Made a mobile order got to the speaker and che...,1,Austin,TX,United States,5
3,4,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",a month ago,My mc Crispy chicken sandwich was customer se...,5,Austin,TX,United States,30
4,5,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",2 months ago,I repeat my order 3 times in the drive thru an...,1,Austin,TX,United States,60

In [35]:
from sqlalchemy import create_engine
engine = create_engine("mysql+mysqlconnector://root:your_password@localhost/mcdonalds_reviews".format(
    user="root",
    password="your_password"
))

# Store data in the database
data.to_sql(name='reviews', con=engine, if_exists='replace', index=False)

33396

In [36]:
import os
from google.cloud import storage

In [37]:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "C:/Users/parabolic-clock-402620.json"

In [53]:
from google.api_core.exceptions import ResourceExhausted
from google.api_core import retry

In [54]:
import time
from google.api_core import retry

@retry.Retry(
    predicate=retry.if_exception_type(ResourceExhausted),
    initial=1,  # start at one second
    maximum=60,  # maximum 60 seconds between retries
    multiplier=2,  # double the wait time on each retry
)
def analyze_sentiment_with_retry(document):
    try:
        sentiment = client.analyze_sentiment(document=document).document_sentiment
        return sentiment.score
    except ResourceExhausted as e:
        print("Quota exceeded, retrying: ", e)
        raise  # This is necessary to trigger the retry

data['sentiment'] = data['review'].apply(lambda text: analyze_sentiment_with_retry(
    language_v1.Document(content=text, type_=language_v1.Document.Type.PLAIN_TEXT)
))

In [55]:
def classify_sentiment(score):
    if score < 0:
        return 'Negative'
    elif score == 0:
        return 'Neutral'
    else:
        return 'Positive'

data['sentiment_label'] = data['sentiment'].apply(classify_sentiment)

In [56]:
data.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating,city,state,country,review_time_in_days,sentiment,sentiment_label
0,1,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",3 months ago,Why does it look like someone spit on my food\...,1,Austin,TX,United States,90,-0.8,Negative
1,2,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Itd McDonalds It is what it is as far as the f...,4,Austin,TX,United States,5,0.9,Positive
2,3,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Made a mobile order got to the speaker and che...,1,Austin,TX,United States,5,-0.6,Negative
3,4,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",a month ago,My mc Crispy chicken sandwich was customer se...,5,Austin,TX,United States,30,0.7,Positive
4,5,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",2 months ago,I repeat my order 3 times in the drive thru an...,1,Austin,TX,United States,60,-0.7,Negative

In [57]:
# Store updated data in the database
data.to_sql(name='reviews', con=engine, if_exists='replace', index=False)

33396